// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      userId: json['userId'] as String,
      userNm: json['userNm'] as String,
      pswd: json['pswd'] as String,
      eml: json['eml'] as String?,
      rprsvNm: json['rprsvNm'] as String,
      bzmnNm: json['bzmnNm'] as String,
      bzmnNo: json['bzmnNo'] as String,
      telno: json['telno'] as String?,
      fxno: json['fxno'] as String?,
      zip: json['zip'] as String,
      addr: json['addr'] as String,
      daddr: json['daddr'] as String,
      bankNm: json['bankNm'] as String,
      dpstrNm: json['dpstrNm'] as String,
      actno: json['actno'] as String,
      mainDrivergn: json['mainDrivergn'] as String,
      avrDriveBgnghr: json['avrDriveBgnghr'] as String?,
      avrDriveEndhr: json['avrDriveEndhr'] as String?,
      vhclNo: json['vhclNo'] as String?,
      vhclLoadLen: json['vhclLoadLen'] as String?,
      vhclLoadweight: json['vhclLoadweight'] as String?,
      vhclType: json['vhclType'] as String?,
      leftAtchfile: json['leftAtchfile'] as String?,
      rightAtchfile: json['rightAtchfile'] as String?,
      backAtchfile: json['backAtchfile'] as String?,
      pnlAtchfile: json['pnlAtchfile'] as String?,
      bzmnrgstrAtchfile: json['bzmnrgstrAtchfile'] as String?,
      consigsignAtchfileSn: json['consigsignAtchfileSn'] as String?,
      aprvYn: json['aprvYn'] as String,
      beaconAddress: json['beaconAddress'] as String?,
      runningAdSn: json['runningAdSn'] as String?,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'userId': instance.userId,
      'userNm': instance.userNm,
      'pswd': instance.pswd,
      'eml': instance.eml,
      'rprsvNm': instance.rprsvNm,
      'bzmnNm': instance.bzmnNm,
      'bzmnNo': instance.bzmnNo,
      'telno': instance.telno,
      'fxno': instance.fxno,
      'zip': instance.zip,
      'addr': instance.addr,
      'daddr': instance.daddr,
      'bankNm': instance.bankNm,
      'dpstrNm': instance.dpstrNm,
      'actno': instance.actno,
      'mainDrivergn': instance.mainDrivergn,
      'vhclNo': instance.vhclNo,
      'vhclLoadLen': instance.vhclLoadLen,
      'vhclLoadweight': instance.vhclLoadweight,
      'vhclType': instance.vhclType,
      'avrDriveBgnghr': instance.avrDriveBgnghr,
      'avrDriveEndhr': instance.avrDriveEndhr,
      'leftAtchfile': instance.leftAtchfile,
      'rightAtchfile': instance.rightAtchfile,
      'backAtchfile': instance.backAtchfile,
      'pnlAtchfile': instance.pnlAtchfile,
      'bzmnrgstrAtchfile': instance.bzmnrgstrAtchfile,
      'consigsignAtchfileSn': instance.consigsignAtchfileSn,
      'aprvYn': instance.aprvYn,
      'beaconAddress': instance.beaconAddress,
      'runningAdSn': instance.runningAdSn,
    };
